name: Static Analysis

on: [ push ]

jobs:
  PHPStan:
    strategy:
      matrix:
        include:
          # Laravel 11.*
          -   php: 8.2
              laravel: 11.*
              composer-flag: '--prefer-stable'
          -   php: 8.3
              laravel: 11.*
              composer-flag: '--prefer-stable'
          -   php: 8.4
              laravel: 11.*
              composer-flag: '--prefer-stable'
          # Laravel 12.*
          -   php: 8.2
              laravel: 12.*
              composer-flag: '--prefer-stable'
          -   php: 8.3
              laravel: 12.*
              composer-flag: '--prefer-stable'
          -   php: 8.4
              laravel: 12.*
              composer-flag: '--prefer-stable'
          -   php: 8.2
              laravel: 12.*
              composer-flag: '--prefer-lowest'
          -   php: 8.3
              laravel: 12.*
              composer-flag: '--prefer-lowest'
          -   php: 8.4
              laravel: 12.*
              composer-flag: '--prefer-lowest'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: "Install dependencies"
        run: composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update

      - name: "Update dependencies"
        run: composer update ${{ matrix.composer-flag }} --prefer-dist --no-interaction

      - name: "Run PhpStan"
        run: composer analyse
